site_name: Dideploy â€” Panduan K3s
site_description: Panduan deploy Kubernetes dengan K3s ke server
site_author: Agung

theme:
  name: material
  language: id
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link

plugins:
  - search
  - git-revision-date-localized:
      type: date

nav:
  - Home: index.md
  - Tutorials:
      - 000 - K3s Memulai: tutorials/000-k3s-getting-started.md
  - How-to Guides:
      - 000 - K3s Multi-Node: how-to/000-k3s-multi-node.md
      - 001 - MetalLB (LoadBalancer): how-to/001-metallb-loadbalancer.md
  - Reference:
      - 000 - Configuration: reference/000-config.md
      - 001 - Traefik (Ingress K3s): reference/001-traefik.md
  - Explanation:
      - 000 - Architecture: explanation/000-architecture.md
